import Head from 'next/head';
import NotFound from '@/components/NotFound';

export default function Custom404() {
  return (
    <>
      <Head>
        <title>Charts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NotFound />
    </>
  );
}
