import Head from 'next/head';

import Container from '@/components/Container';
import {Stack} from '@/components/primitives';

export default function Charts() {
  return (
    <>
      <Head>
        <title>Charts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack className="gap-y-32">
        <Container>
          <Stack className="gap-y-32">

            <Stack className="gap-y-24">
           
            </Stack>

          </Stack>
        </Container>
      </Stack>
    </>
  );
}
