import Head from "next/head";

import Container from "@/components/Container";
import { Stack } from "@/components/primitives";
// import TodoFlowCanvas from "@/components/TodoFlowCanvas";
import TodoFlowCanvas from "@/components/Todos";

export default function Todos() {
  return (
    <>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack className="gap-y-32">
        <Container>
        <h1 className="text-secondary text-2xl text-center font-bold mx-auto">
          Todos Chart
        </h1>
          <TodoFlowCanvas />
        </Container>
      </Stack>
    </>
  );
}
