import Head from "next/head";

import Container from "@/components/Container";
import TodoFlowCanvas from "@/components/Todos";

export default function Todos() {
  return (
    <>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container className="mb-10 h-screen">
        <TodoFlowCanvas />
      </Container>
    </>
  );
}
